/**
 * Auteur·ices connu·es dans Trans-Trame — généré par scripts/extract-authors.mjs
 * Dernière extraction : 2026-04-04
 */
export const KNOWN_AUTHORS: { firstName: string; lastName: string }[] = [
  { firstName: "Michaela Danjé", lastName: "(dir.)" },
  { firstName: "William", lastName: "Acker" },
  { firstName: "Magali", lastName: "Bessone" },
  { firstName: "Rachida", lastName: "Brahim" },
  { firstName: "Solène", lastName: "Brun" },
  { firstName: "Tarana", lastName: "Burke" },
  { firstName: "Ya-Han", lastName: "Chuang" },
  { firstName: "Leïla", lastName: "Cukierman" },
  { firstName: "Anas", lastName: "Daif" },
  { firstName: "Gerty", lastName: "Dambury" },
  { firstName: "Linh-Lan", lastName: "DAO" },
  { firstName: "Samuel", lastName: "Delor" },
  { firstName: "Rokhaya", lastName: "Diallo" },
  { firstName: "Marlene", lastName: "Dos Santos" },
  { firstName: "Sud", lastName: "Éducation 93 (collectif)" },
  { firstName: "Hélène", lastName: "Frappat" },
  { firstName: "Sandra", lastName: "G. Harding" },
  { firstName: "Baptiste", lastName: "Gaudry" },
  { firstName: "Amandine", lastName: "Gay" },
  { firstName: "Baptiste", lastName: "Godrie" },
  { firstName: "Abdellali", lastName: "Hajjat" },
  { firstName: "Kaoutar", lastName: "Harchi" },
  { firstName: "Sandra G.", lastName: "Harding" },
  { firstName: "Frank", lastName: "Lao" },
  { firstName: "Grace", lastName: "Ly" },
  { firstName: "Olivier", lastName: "Marboeuf" },
  { firstName: "Sara", lastName: "Mazouz" },
  { firstName: "Leonora", lastName: "Miano" },
  { firstName: "Marwan", lastName: "Mohammed" },
  { firstName: "Jonas", lastName: "Pardo" },
  { firstName: "Paul B.", lastName: "Preciado" },
  { firstName: "Emmanuel", lastName: "Renault" },
  { firstName: "Nesrine", lastName: "Slaoui" },
  { firstName: "Maboula", lastName: "Soumahoro" },
  { firstName: "", lastName: "Sud Éducation 93 (collectif)" },
  { firstName: "Nancy", lastName: "Tuana" },
  { firstName: "Françoise", lastName: "Vergès" },
  { firstName: "Ilana", lastName: "Weizman" },
]
