// Auto-tagging par mots-clés (utilisé pour détecter les axes dans l’import)
import type { Axis } from './categories.constants'

export const AXIS_KEYWORDS: Record<Axis, string[]> = {
  ECOLOGY: [
    'écologie',
    'ecology',
    'écologis',
    'environnement',
    'environment',
    'climat',
    'climate',
    'écofémin',
    'ecofem',
    'anthropocène',
    'anthropocene',
    'nature',
    'capitalocène',
    'capitalocene',
    'extractivi',
    'biodiversi',
    'durable',
    'sustainable',
    'terre',
    'vivant',
  ],
  QUEER: [
    'queer',
    'trans ',
    'transgenre',
    'transgender',
    'transidentit',
    'non-binaire',
    'nonbinary',
    'non binaire',
    'lgbtq',
    'gender trouble',
    'trouble dans le genre',
    'sexualit',
    'hétéronorm',
    'heteronorm',
    'homonorm',
    'cisgenre',
    'drag',
    'homosexual',
    'lesbien',
    'lesbian',
    'gay',
    'bisexu',
  ],
  AFROFEMINIST: [
    'afrofémin',
    'afrofem',
    'négritude',
    'negritude',
    'black feminis',
    'womanism',
    'bell hooks',
    'audre lorde',
    'angela davis',
    'toni morrison',
    'décolonial',
    'decolonial',
    'postcolonial',
    'panafri',
    'diaspora',
    'afrodescend',
    'néocolonial',
    'neocolonial',
  ],
  ANTIRACISM: [
    'antisem',
    'afro',
    'arabe',
    'asiat',
    'colonis',
    'décolonis',
    'race',
    'blanc',
    'racis',
    'antiracis',
    'anti-racis',
    'racial',
    'blanchité',
    'whiteness',
    'privilège blanc',
    'white privilege',
    'ségrégation',
    'segregation',
    'discriminat',
    'islamophob',
    'xénophob',
    'xenophob',
    'minorit',
    'racisé',
    'racialized',
    'coloris',
  ],
  CHILDHOOD: [
    'enfance',
    'childhood',
    'family',
    'parental',
    'parenting',
    'parent',
    'mère',
    'père',
    'frère',
    'sœur',
    'grand-mère',
    'grand-père',
    'grand-frère',
    'grand-sœur',
    'grand-mère',
    'grand-père',
    'grand-frère',
    'grand-sœur',
    'incest',
  ],
  HEALTH: [
    'santé',
    'health',
    'trauma',
    'psychi',
    'soin',
    'care ',
    'médical',
    'medical',
    'thérap',
    'therap',
    'guéri',
    'healing',
    'maladie',
    'illness',
    'douleur',
    'pain',
    'corps',
    'body',
    'violenc',
    'abus',
    'surviv',
    'résilience',
    'resilience',
    'burn.?out',
    'deuil',
    'grief',
  ],
  CRIP: [
    'handicap',
    'disabilit',
    'crip',
    'validis',
    'ableism',
    'capacitis',
    'accessibil',
    'inclusion',
    'neurodivergen',
    'autis',
    'surd',
    'sourd',
    'aveugle',
    'blind',
    'fauteuil',
    'wheelchair',
    'mad studies',
  ],
  HISTORY: [
    'histoir',
    'history',
    'historical',
    'historique',
    'mémoir',
    'memoir',
    'archives',
    'archéolog',
    'archaeolog',
    'généalog',
    'genealog',
    'antiquit',
    'médiéval',
    'medieval',
    'révolution',
    'revolution',
    'guerre',
    'war ',
    'siècle',
    'century',
    'époque',
    'colonial',
  ],
  INSTITUTIONAL: [
    'institution',
    'politique',
    'politic',
    'état',
    'state',
    'gouvern',
    'govern',
    'droit',
    'law ',
    'legal',
    'juridiq',
    'législat',
    'legislat',
    'universi',
    'académi',
    'academ',
    'sociolog',
    'économi',
    'econom',
    'néolibéral',
    'neoliberal',
    'capitalisme',
    'capitalism',
    'bureaucra',
    'administrat',
    'parlement',
    'parliament',
  ],
} as const

